% create simple interval mesh
% ele and node files

N    = 100;
Nele = N-1;
Nphi =   2;
Nattr=   1;

x = linspace(0,1,N);

ele = zeros(N-1,2);

ele(:,1)=1:(N-1);
ele(:,2)=2:N;

idv    = zeros(N,1);
idv(1) = 1;
idv(N) = 1;

ide    = ones(Nele,1);

fid = fopen('mesh1.node','w');
fprintf(fid,'%i %i %i %i\n',N,1,0,1);
for i=1:N
    fprintf(fid,'%i %e %i\n',i,x(i),idv(i));
end
fprintf(fid,'# generated by mesh1.m\n')
fclose(fid);

fid = fopen('mesh1.ele','w');
fprintf(fid,'%i %i %i\n',Nele,Nphi,Nattr);
for i=1:Nele
    fprintf(fid,'%i %i %i %i\n',i,ele(i,1),ele(i,2),ide(i));
end
fprintf(fid,'# generated by mesh1.m\n')
fclose(fid)
